export const URL_LOGIN = '/auth/login'
export const URL_REGISTER = '/auth/register'
export const URL_LOGGEDIN_USER = '/auth/user'
export const URL_USERS = '/users'
export const URL_GROUPS = '/groups'

export const URL_INDUSTRY = '/industries'
export const URL_CAREER = '/careers'
export const URL_FIELD = '/fields'
export const URL_TASK = '/tasks'
export const URL_SKILL = '/skills'
export const URL_TOPIC = '/topics'
export const URL_METRICS = '/metrics'
export const URL_QUESTION = '/questions'
export const URL_ASSESSMENT = '/assessments'
export const URL_CONFIG = '/config'
export const URL_STORAGE = '/storage'

export const URL_TALENTS = '/talents'
export const URL_LIBRARIES = '/libraries'
export const URL_MODULES = '/modules'
export const URL_LESSONS = '/lessons'
