export type IconName = '';
export type SizeType = 'mini' | 'xsm' | 'sm' | 'rg' | 'default' | 'md' | 'lg' | 'xlg' | 'xxlg' | 'lgr';
export type SemanticType = 'info' | 'warning' | 'success' | 'error' | 'ongoing'
export type ButtonType = 'primary' | 'ghost' | 'icon' | 'link'
export type RouteParamType = 'url' | 'query';
export type RouteActionType = 'navigate' | 'open-secondary' | 'logout';
export type UserType = 'superadmin' | 'admin' | 'business' | 'talent' | 'user';
export type ApiServiceType = 'identity' | 'core' | 'genius' | 'resource';
export type ApiMethodType = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export type NavItemType = 'sidebar' | 'navbar' | 'topbar';