export type IconName = '';
export type IconFamilyType = 'polio' | 'fa' | 'feather';
export type SizeType = 'mini' | 'msm' | 'xsm' | 'sm' | 'rg' | 'default' | 'md' | 'lg' | 'xlg' | 'xxlg' | 'lgr';
export type SemanticType = 'info' | 'warning' | 'warning-2' | 'success' | 'error' | 'ongoing' | 'normal';
export type ButtonType = 'primary' | 'ghost' | 'icon' | 'link'
export type RouteParamType = 'url' | 'query' | 'path';
export type RouteActionType = 'navigate' | 'open-secondary' | 'logout';
export type UserType = 'superadmin' | 'admin' | 'business' | 'talent' | 'user';
export type ApiServiceType = 'identity' | 'core' | 'genius' | 'resource';
export type ApiMethodType = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export type NavItemType = 'sidebar' | 'navbar' | 'topbar';
export type LoadingType = 'default' | 'resource'
export type QueryOrderType = 'desc' | 'asc'
export type StatusType = 'enabled' | 'active' | 'status'
export type PositionType = 'top' | 'top-left' | 'top-right' | 'bottom' | 'bottom-left' | 'bottom-right' | 'left' | 'right'
export type LevelType = 'default' | 'novice' | 'beginner' | 'intermediate' | 'advanced' | 'professional'
export type DifficultyType = 'random' | 'easy' | 'normal' | 'hard' | 'difficult'
export type QuestionType = 'trivial' | 'career' | 'general'
export type RubricType = 'level' | 'question-type' | 'difficulty' | 'score' | 'time'
export type FlexReverseType = 'row' | 'column' | 'default';
export type FontWeightType = 100 | 'thin' | 200 | 'xlight' | 300 | 'light' | 400 | 'regular' | 500 | 'medium' | 600 | 'semibold' | 700 | 'bold' | 800 | 'xbold' | 900 | 'black' | 'heavy'; 
export type FormActionType = 'edit-resource' | 'add-resource';
export type UIDisplayType = 'list' | 'table' | 'single' | 'details';
export type FileAcceptType = 'csv' | 'sheet' | 'pdf' | 'image' | 'video' | 'audo';
export type CSVAcceptType = '.csv' | '.xls' | 'application/vnd.ms-excel' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
export type TextAcceptType = 'text/plain' | 'text/html'
export type VideoAcceptType = 'video/*'
export type AudioAcceptType = 'audio/*'
export type PDFAcceptType = '.pdf' | 'application/pdf'
export type ImageAcceptType = 'image/x-png' | 'image/jpg' | 'image/jpeg' | 'image/png' | 'image/svg' | 'image/gif' | 'image/*' | 'image/x-eps'
export type ResourceType = 'user' | 'users' | 'industry' | 'industries' | 'career' | 'careers' | 'field' | 'fields' | 'skill' | 'skills' | 'topic' | 'topics' | 'question' | 'questions'
export type FilterType = 'default' | 'user' | 'industry' | 'career' | 'field' | 'skill' | 'topic' | 'question'
export type PagesearchType = 'search' | 'filter'